import type { Property, User, PrivacyType } from '@/types';

export const dummyUsers: User[] = [
  { id: 'user-1', name: 'Regular Joe', email: 'user@stayfinder.com', password: 'password123', avatar: 'https://placehold.co/100x100.png', role: 'user', verificationStatus: 'unverified', wishlist: [] },
  { id: 'user-2', name: 'Host Henrietta', email: 'host@stayfinder.com', password: 'password123', avatar: 'https://placehold.co/100x100.png', role: 'host', verificationStatus: 'pending', identityDocumentUrl: 'https://placehold.co/800x600.png', wishlist: [] },
  { id: 'user-3', name: 'Admin Adam', email: 'admin@stayfinder.com', password: 'password123', avatar: 'https://placehold.co/100x100.png', role: 'super-admin', verificationStatus: 'verified', wishlist: [] },
];


export const properties: Property[] = [
  {
    id: '1',
    name: 'Serene Beachfront Villa',
    location: 'Malibu, California',
    pricePerNight: 70000,
    description: 'Experience luxury living in this stunning beachfront villa with panoramic ocean views. Perfect for a relaxing getaway.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Pool', 'Kitchen', 'Free parking', 'Beach access', 'Air conditioning'],
    rating: 4.9,
    reviewsCount: 120,
    host: {
      id: 'host-1',
      name: 'Alice Johnson',
      email: 'host1@stayfinder.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'Villa',
    privacyType: 'entire-place',
    bedrooms: 4,
    beds: 4,
    baths: 4,
    maxGuests: 8,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
  {
    id: '2',
    name: 'Cozy Mountain Cabin',
    location: 'Aspen, Colorado',
    pricePerNight: 25000,
    description: 'A charming and cozy cabin nestled in the heart of the mountains. Ideal for ski trips and nature lovers.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Indoor fireplace', 'Kitchen', 'Free parking', 'Hot tub'],
    rating: 4.8,
    reviewsCount: 250,
    host: {
      id: 'host-2',
      name: 'Bob Richards',
      email: 'host2@stayfinder.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'House',
    privacyType: 'entire-place',
    bedrooms: 2,
    beds: 2,
    baths: 2,
    maxGuests: 4,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
  {
    id: '3',
    name: 'Modern Downtown Loft',
    location: 'New York, New York',
    pricePerNight: 35000,
    description: 'Stylish and modern loft in the bustling heart of the city. Steps away from famous landmarks, restaurants, and shops.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Kitchen', 'Elevator', 'Air conditioning', 'City view'],
    rating: 4.7,
    reviewsCount: 300,
    host: {
      id: 'host-3',
      name: 'Charlie Davis',
      email: 'host3@stayfinder.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'Apartment',
    privacyType: 'entire-place',
    bedrooms: 1,
    beds: 1,
    baths: 1,
    maxGuests: 2,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
  {
    id: '4',
    name: 'Luxury Penthouse with Rooftop',
    location: 'Miami, Florida',
    pricePerNight: 90000,
    description: 'Indulge in this exclusive penthouse with a private rooftop terrace and stunning city and ocean views.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Pool', 'Kitchen', 'Free parking', 'Rooftop access', 'Gym'],
    rating: 5.0,
    reviewsCount: 80,
    host: {
      id: 'host-4',
      name: 'Diana Prince',
      email: 'host4@stayfinder.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'Condo',
    privacyType: 'entire-place',
    bedrooms: 3,
    beds: 3,
    baths: 3,
    maxGuests: 6,
    status: 'pending',
    bookingPolicy: 'review-first',
  },
  {
    id: '5',
    name: 'Rustic Countryside Farmhouse',
    location: 'Tuscany, Italy',
    pricePerNight: 22000,
    description: 'A beautiful, restored farmhouse in the rolling hills of Tuscany. Enjoy authentic Italian countryside living.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Kitchen', 'Free parking', 'Garden', 'Pet friendly'],
    rating: 4.9,
    reviewsCount: 180,
    host: {
      id: 'host-5',
      name: 'Giovanni Rossi',
      email: 'host5@stayfinder.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'House',
    privacyType: 'entire-place',
    bedrooms: 3,
    beds: 3,
    baths: 2,
    maxGuests: 7,
    status: 'pending',
    bookingPolicy: 'review-first',
  },
  {
    id: '6',
    name: 'Chic Parisian Apartment',
    location: 'Paris, France',
    pricePerNight: 30000,
    description: 'Live like a Parisian in this chic and elegant apartment with a view of the Eiffel Tower.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Kitchen', 'Elevator', 'Air conditioning', 'Balcony'],
    rating: 4.8,
    reviewsCount: 220,
    host: {
      id: 'host-6',
      name: 'Amélie Dubois',
      email: 'host6@stayfinder.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'Apartment',
    privacyType: 'entire-place',
    bedrooms: 1,
    beds: 1,
    baths: 1,
    maxGuests: 3,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
  {
    id: '7',
    name: 'Lakeside Retreat',
    location: 'Lake Tahoe, California',
    pricePerNight: 45000,
    description: 'A stunning retreat right on the shores of Lake Tahoe. Enjoy water sports in summer and skiing in winter.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Kitchen', 'Free parking', 'Lake access', 'Hot tub', 'Boat slip'],
    rating: 4.9,
    reviewsCount: 155,
    host: {
      id: 'host-7',
      name: 'Frank Miller',
      email: 'host7@stayfinder.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'House',
    privacyType: 'entire-place',
    bedrooms: 4,
    beds: 4,
    baths: 3,
    maxGuests: 10,
    status: 'rejected',
    bookingPolicy: 'review-first',
  },
  {
    id: '8',
    name: 'Urban Oasis with Garden',
    location: 'London, United Kingdom',
    pricePerNight: 32000,
    description: 'A rare find in London - a stylish flat with its own private garden oasis. Perfect for relaxing after a day of exploring.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Kitchen', 'Garden', 'Washer', 'Dishwasher'],
    rating: 4.7,
    reviewsCount: 190,
    host: {
      id: 'host-8',
      name: 'Grace Kelly',
      email: 'host8@stayfinder.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'Apartment',
    privacyType: 'entire-place',
    bedrooms: 2,
    beds: 2,
    baths: 1,
    maxGuests: 4,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
  {
    id: '9',
    name: 'Tokyo Tech Flat',
    location: 'Shibuya, Tokyo, Japan',
    pricePerNight: 28000,
    description: 'A sleek, modern flat in the heart of Shibuya, equipped with the latest technology for a comfortable and convenient stay.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Washer', 'TV'],
    rating: 4.9,
    reviewsCount: 210,
    host: {
      id: 'host-9',
      name: 'Ken Tanaka',
      email: 'host9@stayfinder.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'Apartment',
    privacyType: 'entire-place',
    bedrooms: 1,
    beds: 1,
    baths: 1,
    maxGuests: 2,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
  {
    id: '10',
    name: 'Sydney Harbour View Studio',
    location: 'Sydney, Australia',
    pricePerNight: 31000,
    description: 'Wake up to breathtaking views of the Sydney Harbour Bridge and Opera House from this stylish studio apartment.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Pool', 'Gym'],
    rating: 4.8,
    reviewsCount: 175,
    host: {
      id: 'host-10',
      name: 'Olivia Smith',
      email: 'host10@stayfinder.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'Apartment',
    privacyType: 'entire-place',
    bedrooms: 0,
    beds: 1,
    baths: 1,
    maxGuests: 2,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
  {
    id: '11',
    name: 'Historic Riad in Marrakech',
    location: 'Marrakech, Morocco',
    pricePerNight: 18000,
    description: 'Experience traditional Moroccan hospitality in this beautifully restored Riad in the heart of the Medina.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Pool', 'Indoor fireplace', 'Garden', 'Kitchen'],
    rating: 4.9,
    reviewsCount: 240,
    host: {
      id: 'host-11',
      name: 'Fatima Al-Fassi',
      email: 'host11@stayfinder.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'Riad',
    privacyType: 'entire-place',
    bedrooms: 4,
    beds: 5,
    baths: 4,
    maxGuests: 10,
    status: 'pending',
    bookingPolicy: 'review-first',
  },
  {
    id: '12',
    name: 'Eco Treehouse in Costa Rica',
    location: 'Monteverde, Costa Rica',
    pricePerNight: 20000,
    description: 'Live among the treetops in this unique and sustainable treehouse, surrounded by the lush Costa Rican rainforest.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Kitchen', 'Free parking', 'Garden'],
    rating: 5.0,
    reviewsCount: 95,
    host: {
      id: 'host-12',
      name: 'Carlos Hernandez',
      email: 'host12@stayfinder.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'Tree house',
    privacyType: 'entire-place',
    bedrooms: 1,
    beds: 1,
    baths: 1,
    maxGuests: 2,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
];

export const allAmenities = Array.from(new Set(properties.flatMap(p => p.amenities))).sort();

export const helpTopics = [
  {
    category: 'Searching and booking',
    links: [
      { title: 'Search tips', href: '#' },
      { title: 'Booking places to stay', href: '#' },
      { title: 'Booking Experiences', href: '#' },
      { title: 'Booking business travel and events', href: '#' },
      { title: 'Messaging', href: '#' },
      { title: 'Travel insurance and reservation insurance', href: '#' },
    ],
  },
  {
    category: 'Your reservations',
    links: [
      { title: 'Reservation status', href: '#' },
      { title: 'Changes', href: '#' },
      { title: 'Cancellations', href: '/cancellation-policy' },
      { title: 'Checking in', href: '#' },
      { title: 'Checking out', href: '#' },
      { title: 'Preparing for an Experience', href: '#' },
      { title: 'Fixing reservation issues', href: '#' },
    ],
  },
  {
    category: 'Payments and pricing',
    links: [
      { title: 'Paying for a reservation', href: '#' },
      { title: 'Refunds', href: '#' },
      { title: 'Pricing and fees', href: '#' },
      { title: 'Coupons, credits, and gift cards', href: '#' },
      { title: 'Invoices and receipts', href: '#' },
      { title: 'Taxes', href: '#' },
    ],
  },
  {
    category: 'Your account and reviews',
    links: [
      { title: 'Creating an account', href: '/signup' },
      { title: 'Managing your account', href: '/account/settings' },
      { title: 'ID and verification', href: '/account/settings' },
      { title: 'Account security', href: '#' },
      { title: 'Reviews', href: '#' },
    ],
  },
  {
    category: 'Safety and accessibility',
    links: [
      { title: 'Safety concerns', href: '/support/safety' },
      { title: 'Safety tips and guidelines', href: '#' },
      { title: 'Reporting issues', href: '#' },
      { title: 'Government travel restrictions and advisories', href: '#' },
    ],
  },
  {
    category: 'About StayFinder',
    links: [
      { title: 'Getting started', href: '#' },
      { title: 'How StayFinder works', href: '#' },
      { title: 'Our community policies', href: '#' },
      { title: 'Partnerships', href: '#' },
    ],
  },
];
