
import type { Property, User, PrivacyType } from '@/types';

export const dummyUsers: User[] = [
  // Users will now be created via the signup form or super-admin auto-creation.
  // This array is kept for type reference but is no longer used for seeding.
];


export const properties: Property[] = [
  {
    id: 'prop-1',
    name: 'Serene Beachfront Villa',
    location: 'Malibu, California',
    pricePerNight: 70000,
    description: 'Experience luxury living in this stunning beachfront villa with panoramic ocean views. Perfect for a relaxing getaway.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Pool', 'Kitchen', 'Free parking', 'Beach access', 'Air conditioning'],
    rating: 4.9,
    reviewsCount: 120,
    host: {
      id: 'host-1',
      name: 'Alice Johnson',
      email: 'host1@tripsandstay.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'Villa',
    privacyType: 'entire-place',
    bedrooms: 4,
    beds: 4,
    baths: 4,
    maxGuests: 8,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
  {
    id: 'prop-2',
    name: 'Cozy Mountain Cabin',
    location: 'Aspen, Colorado',
    pricePerNight: 25000,
    description: 'A charming and cozy cabin nestled in the heart of the mountains. Ideal for ski trips and nature lovers.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Indoor fireplace', 'Kitchen', 'Free parking', 'Hot tub'],
    rating: 4.8,
    reviewsCount: 250,
    host: {
      id: 'host-2',
      name: 'Bob Richards',
      email: 'host2@tripsandstay.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'House',
    privacyType: 'entire-place',
    bedrooms: 2,
    beds: 2,
    baths: 2,
    maxGuests: 4,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
  {
    id: 'prop-3',
    name: 'Modern Downtown Loft',
    location: 'New York, New York',
    pricePerNight: 35000,
    description: 'Stylish and modern loft in the bustling heart of the city. Steps away from famous landmarks, restaurants, and shops.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Kitchen', 'Elevator', 'Air conditioning', 'City view'],
    rating: 4.7,
    reviewsCount: 300,
    host: {
      id: 'host-3',
      name: 'Charlie Davis',
      email: 'host3@tripsandstay.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'Apartment',
    privacyType: 'entire-place',
    bedrooms: 1,
    beds: 1,
    baths: 1,
    maxGuests: 2,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
  {
    id: 'prop-4',
    name: 'Luxury Penthouse with Rooftop',
    location: 'Miami, Florida',
    pricePerNight: 90000,
    description: 'Indulge in this exclusive penthouse with a private rooftop terrace and stunning city and ocean views.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Pool', 'Kitchen', 'Free parking', 'Rooftop access', 'Gym'],
    rating: 5.0,
    reviewsCount: 80,
    host: {
      id: 'host-4',
      name: 'Diana Prince',
      email: 'host4@tripsandstay.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'Condo',
    privacyType: 'entire-place',
    bedrooms: 3,
    beds: 3,
    baths: 3,
    maxGuests: 6,
    status: 'pending',
    bookingPolicy: 'review-first',
  },
  {
    id: 'prop-5',
    name: 'Rustic Countryside Farmhouse',
    location: 'Tuscany, Italy',
    pricePerNight: 22000,
    description: 'A beautiful, restored farmhouse in the rolling hills of Tuscany. Enjoy authentic Italian countryside living.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Kitchen', 'Free parking', 'Garden', 'Pet friendly'],
    rating: 4.9,
    reviewsCount: 180,
    host: {
      id: 'host-5',
      name: 'Giovanni Rossi',
      email: 'host5@tripsandstay.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'House',
    privacyType: 'entire-place',
    bedrooms: 3,
    beds: 3,
    baths: 2,
    maxGuests: 7,
    status: 'pending',
    bookingPolicy: 'review-first',
  },
  {
    id: 'prop-6',
    name: 'Chic Parisian Apartment',
    location: 'Paris, France',
    pricePerNight: 30000,
    description: 'Live like a Parisian in this chic and elegant apartment with a view of the Eiffel Tower.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Kitchen', 'Elevator', 'Air conditioning', 'Balcony'],
    rating: 4.8,
    reviewsCount: 220,
    host: {
      id: 'host-6',
      name: 'Amélie Dubois',
      email: 'host6@tripsandstay.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'Apartment',
    privacyType: 'entire-place',
    bedrooms: 1,
    beds: 1,
    baths: 1,
    maxGuests: 3,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
  {
    id: 'prop-9',
    name: 'Tokyo Tech Flat',
    location: 'Shibuya, Tokyo, Japan',
    pricePerNight: 28000,
    description: 'A sleek, modern flat in the heart of Shibuya, equipped with the latest technology for a comfortable and convenient stay.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Washer', 'TV'],
    rating: 4.9,
    reviewsCount: 210,
    host: {
      id: 'host-9',
      name: 'Ken Tanaka',
      email: 'host9@tripsandstay.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'Apartment',
    privacyType: 'entire-place',
    bedrooms: 1,
    beds: 1,
    baths: 1,
    maxGuests: 2,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
  {
    id: 'prop-10',
    name: 'Sydney Harbour View Studio',
    location: 'Sydney, Australia',
    pricePerNight: 31000,
    description: 'Wake up to breathtaking views of the Sydney Harbour Bridge and Opera House from this stylish studio apartment.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Pool', 'Gym'],
    rating: 4.8,
    reviewsCount: 175,
    host: {
      id: 'host-10',
      name: 'Olivia Smith',
      email: 'host10@tripsandstay.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'Apartment',
    privacyType: 'entire-place',
    bedrooms: 0,
    beds: 1,
    baths: 1,
    maxGuests: 2,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
  {
    id: 'prop-11',
    name: 'Historic Riad in Marrakech',
    location: 'Marrakech, Morocco',
    pricePerNight: 18000,
    description: 'Experience traditional Moroccan hospitality in this beautifully restored Riad in the heart of the Medina.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Pool', 'Indoor fireplace', 'Garden', 'Kitchen'],
    rating: 4.9,
    reviewsCount: 240,
    host: {
      id: 'host-11',
      name: 'Fatima Al-Fassi',
      email: 'host11@tripsandstay.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'Riad',
    privacyType: 'entire-place',
    bedrooms: 4,
    beds: 5,
    baths: 4,
    maxGuests: 10,
    status: 'pending',
    bookingPolicy: 'review-first',
  },
  {
    id: 'prop-12',
    name: 'Eco Treehouse in Costa Rica',
    location: 'Monteverde, Costa Rica',
    pricePerNight: 20000,
    description: 'Live among the treetops in this unique and sustainable treehouse, surrounded by the lush Costa Rican rainforest.',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Kitchen', 'Free parking', 'Garden', 'Pet friendly'],
    rating: 5.0,
    reviewsCount: 95,
    host: {
      id: 'host-12',
      name: 'Carlos Hernandez',
      email: 'host12@tripsandstay.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'Tree house',
    privacyType: 'entire-place',
    bedrooms: 1,
    beds: 1,
    baths: 1,
    maxGuests: 2,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
  {
    id: 'prop-13',
    name: 'Krishnaaa',
    location: 'Mumbai',
    pricePerNight: 1500,
    description: 'this is a good hotel',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Pet friendly'],
    rating: 0,
    reviewsCount: 0,
    host: {
      id: 'host-13',
      name: 'Damini Chachane',
      email: 'daminichachan@gmail.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'House',
    privacyType: 'entire-place',
    bedrooms: 4,
    beds: 4,
    baths: 4,
    maxGuests: 8,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
  {
    id: 'prop-14',
    name: 'Beach Resorttt',
    location: 'Nagpur',
    pricePerNight: 1500,
    description: 'nice',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Pet friendly'],
    rating: 0,
    reviewsCount: 0,
    host: {
      id: 'host-14',
      name: 'Damini Chachane',
      email: 'daminichachan@gmail.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'House',
    privacyType: 'entire-place',
    bedrooms: 4,
    beds: 4,
    baths: 4,
    maxGuests: 8,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
  {
    id: 'prop-15',
    name: 'TripsandStay Hotel',
    location: 'Demonn',
    pricePerNight: 2500,
    description: 'nice',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Pet friendly'],
    rating: 0,
    reviewsCount: 0,
    host: {
      id: 'host-15',
      name: 'Damini Chachane',
      email: 'daminichachan@gmail.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'House',
    privacyType: 'entire-place',
    bedrooms: 4,
    beds: 4,
    baths: 4,
    maxGuests: 8,
    status: 'approved',
    bookingPolicy: 'review-first',
  },
  {
    id: 'prop-16',
    name: 'Templeeeeeeeeeee',
    location: 'Nagpur',
    pricePerNight: 1500,
    description: 'its a temple',
    image1: 'https://placehold.co/800x600.png',
    image2: 'https://placehold.co/600x400.png',
    image3: 'https://placehold.co/600x400.png',
    image4: 'https://placehold.co/600x400.png',
    amenities: ['WiFi', 'Pet friendly'],
    rating: 0,
    reviewsCount: 0,
    host: {
      id: 'host-16',
      name: 'Damini Chachane',
      email: 'daminichachan@gmail.com',
      avatar: 'https://placehold.co/100x100.png',
      role: 'host',
      verificationStatus: 'verified',
    },
    type: 'House',
    privacyType: 'entire-place',
    bedrooms: 4,
    beds: 4,
    baths: 4,
    maxGuests: 8,
    status: 'approved',
    bookingPolicy: 'review-first',
  }
];

export const allAmenities = Array.from(new Set(properties.flatMap(p => p.amenities))).sort();

export const helpTopics = [
  {
    category: 'Searching and booking',
    links: [
      { title: 'Search tips', href: '#' },
      { title: 'Booking places to stay', href: '#' },
      { title: 'Booking Experiences', href: '#' },
      { title: 'Booking business travel and events', href: '#' },
      { title: 'Messaging', href: '#' },
      { title: 'Travel insurance and reservation insurance', href: '#' },
    ],
  },
  {
    category: 'Your reservations',
    links: [
      { title: 'Reservation status', href: '#' },
      { title: 'Changes', href: '#' },
      { title: 'Cancellations', href: '/cancellation-policy' },
      { title: 'Checking in', href: '#' },
      { title: 'Checking out', href: '#' },
      { title: 'Preparing for an Experience', href: '#' },
      { title: 'Fixing reservation issues', href: '#' },
    ],
  },
  {
    category: 'Payments and pricing',
    links: [
      { title: 'Paying for a reservation', href: '#' },
      { title: 'Refunds', href: '#' },
      { title: 'Pricing and fees', href: '#' },
      { title: 'Coupons, credits, and gift cards', href: '#' },
      { title: 'Invoices and receipts', href: '#' },
      { title: 'Taxes', href: '#' },
    ],
  },
  {
    category: 'Your account and reviews',
    links: [
      { title: 'Creating an account', href: '/signup' },
      { title: 'Managing your account', href: '/account/settings' },
      { title: 'ID and verification', href: '/account/settings' },
      { title: 'Account security', href: '#' },
      { title: 'Reviews', href: '#' },
    ],
  },
  {
    category: 'Safety and accessibility',
    links: [
      { title: 'Safety concerns', href: '/support/safety' },
      { title: 'Safety tips and guidelines', href: '#' },
      { title: 'Reporting issues', href: '#' },
      { title: 'Government travel restrictions and advisories', href: '#' },
    ],
  },
  {
    category: 'About TripsandStay',
    links: [
      { title: 'Getting started', href: '#' },
      { title: 'How TripsandStay works', href: '#' },
      { title: 'Our community policies', href: '#' },
      { title: 'Partnerships', href: '#' },
    ],
  },
];

export const homeHostHelpTopics = [
  {
    category: 'About hosting',
    links: [
      { title: 'Hosting your home', href: '#' },
      { title: 'Ways to host', href: '#' },
      { title: 'Protection and insurance', href: '#' },
      { title: 'Regulations and standards', href: '#' },
      { title: 'Airbnb.org', href: '#' },
      { title: 'Airbnb Luxe', href: '#' },
    ],
  },
  {
    category: 'Calendar and bookings',
    links: [
      { title: 'Booking enquiries', href: '#' },
      { title: 'Your booking requirements', href: '#' },
      { title: 'Managing your calendar', href: '#' },
      { title: 'Pre-approvals and special offers', href: '#' },
    ],
  },
  {
    category: 'Payouts and taxes',
    links: [
      { title: 'How payouts work', href: '#' },
      { title: 'Payout methods', href: '#' },
      { title: 'Payout details and preferences', href: '#' },
      { title: 'Fixing payout issues', href: '#' },
      { title: 'Taxes', href: '#' },
      { title: 'Donations', href: '#' },
    ],
  },
  {
    category: 'Managing your listing',
    links: [
      { title: 'Listing details', href: '#' },
      { title: 'Pricing', href: '#' },
      { title: 'Listing availability', href: '#' },
      { title: 'Booking settings and Instant Book', href: '#' },
      { title: 'Marketing and promoting your listing', href: '#' },
    ],
  },
  {
    category: 'Professional hosting tools',
    links: [{ title: 'Using other hosting software', href: '#' }],
  },
  {
    category: 'Your reservations',
    links: [
      { title: 'How reservations work', href: '#' },
      { title: 'Cancellations', href: '#' },
      { title: 'Changes', href: '#' },
      { title: 'Guest refunds and reimbursements', href: '#' },
      { title: 'Issues with a reservation', href: '#' },
      { title: 'Messaging with guests', href: '#' },
    ],
  },
  {
    category: 'About Airbnb',
    links: [
      { title: 'Getting started', href: '#' },
      { title: 'How Airbnb works', href: '#' },
      { title: 'Our community policies', href: '#' },
      { title: 'Partnerships', href: '#' },
    ],
  },
  {
    category: 'Your account and reviews',
    links: [
      { title: 'Creating an account', href: '#' },
      { title: 'Managing your account', href: '#' },
      { title: 'ID and verification', href: '#' },
      { title: 'Account security', href: '#' },
      { title: 'Reviews', href: '#' },
    ],
  },
  {
    category: 'Safety and accessibility',
    links: [
      { title: 'Safety concerns', href: '#' },
      { title: 'Safety tips and guidelines', href: '#' },
      { title: 'Reporting issues', href: '#' },
      { title: 'Government travel restrictions and advisories', href: '#' },
    ],
  },
  {
    category: 'Local rules and regulations',
    links: [
      { title: 'Asia-Pacific', href: '#' },
      { title: 'Responsible hosting for places to stay in Europe', href: '#' },
      { title: 'North America', href: '#' },
      { title: 'South America', href: '#' },
      { title: 'Africa', href: '#' },
    ],
  },
];

export const experienceHostHelpTopics = [
    {
      category: 'About hosting',
      links: [
        { title: 'Experience hosting basics', href: '#' },
        { title: 'Preparing to host an experience', href: '#' },
        { title: 'Experience categories', href: '#' },
        { title: 'Co-hosting experiences', href: '#' },
        { title: 'Protection and insurance', href: '#' },
      ],
    },
    {
      category: 'Managing your experience',
      links: [
        { title: 'Calendar and bookings', href: '#' },
        { title: 'Updating your experience page', href: '#' },
        { title: 'Pricing your experience', href: '#' },
        { title: 'Marketing and promotion', href: '#' },
      ],
    },
    {
      category: 'Your reservations',
      links: [
        { title: 'Changes and cancellations', href: '#' },
        { title: 'Refunds and reimbursements', href: '#' },
        { title: 'Communicating with guests', href: '#' },
        { title: 'Issues with a reservation', href: '#' },
      ],
    },
    {
        category: 'Payouts and taxes',
        links: [
            { title: 'Payouts', href: '#' },
            { title: 'Taxes', href: '#' }
        ]
    },
    {
        category: 'About Airbnb',
        links: [
            { title: 'Getting started', href: '#' },
            { title: 'How Airbnb works', href: '#' },
            { title: 'Our community policies', href: '#' },
            { title: 'Partnerships', href: '#' },
        ]
    },
    {
        category: 'Your account and reviews',
        links: [
            { title: 'Creating an account', href: '#' },
            { title: 'Managing your account', href: '#' },
            { title: 'ID and verification', href: '#' },
            { title: 'Account security', href: '#' },
            { title: 'Reviews', href: '#' },
        ]
    },
    {
        category: 'Safety and accessibility',
        links: [
            { title: 'Safety concerns', href: '#' },
            { title: 'Safety tips and guidelines', href: '#' },
            { title: 'Reporting issues', href: '#' },
            { title: 'Government travel restrictions and advisories', href: '#' },
        ]
    },
    {
        category: 'Local rules and regulations for Airbnb Experiences',
        links: [
            { title: 'General info', href: '#' },
            { title: 'Asia-Pacific', href: '#' },
        ]
    }
];

export const serviceHostHelpTopics = [
    {
        category: 'About hosting',
        links: [
            { title: 'Service hosting basics', href: '#' },
            { title: 'Preparing to host a service', href: '#' },
            { title: 'Protection and insurance', href: '#' },
            { title: 'Service categories and guidelines', href: '#' },
        ]
    },
    {
        category: 'Managing your service',
        links: [
            { title: 'Calendar and bookings', href: '#' },
            { title: 'Updating your service page', href: '#' },
            { title: 'Pricing your service', href: '#' },
        ]
    },
    {
        category: 'Your reservations',
        links: [
            { title: 'Changes and cancellations', href: '#' },
            { title: 'Refunds and reimbursements', href: '#' },
            { title: 'Communicating with guests', href: '#' },
            { title: 'Issues with a reservation', href: '#' },
        ]
    },
    {
        category: 'Payouts and taxes',
        links: [
            { title: 'Payouts', href: '#' },
            { title: 'Taxes', href: '#' }
        ]
    },
    {
        category: 'About Airbnb',
        links: [
            { title: 'Getting started', href: '#' },
            { title: 'How Airbnb works', href: '#' },
            { title: 'Our community policies', href: '#' },
            { title: 'Partnerships', href: '#' },
        ]
    },
    {
        category: 'Your account and reviews',
        links: [
            { title: 'Creating an account', href: '#' },
            { title: 'Managing your account', href: '#' },
            { title: 'ID and verification', href: '#' },
            { title: 'Account security', href: '#' },
            { title: 'Reviews', href: '#' },
        ]
    },
    {
        category: 'Safety and accessibility',
        links: [
            { title: 'Safety concerns', href: '#' },
            { title: 'Safety tips and guidelines', href: '#' },
            { title: 'Reporting issues', href: '#' },
            { title: 'Government travel restrictions and advisories', href: '#' },
        ]
    },
    {
        category: 'Local rules and regulations for Airbnb Services',
        links: [
            { title: 'General info', href: '#' },
            { title: 'Service categories and guidelines', href: '#' },
        ]
    }
];

export const travelAdminHelpTopics = [
    {
        category: 'Airbnb for Work basics',
        links: [
            { title: 'Airbnb for Work basics', href: '#' },
            { title: 'Signing up', href: '#' },
            { title: 'Your company\'s Airbnb for Work account', href: '#' },
        ]
    },
    {
        category: 'Managing employees',
        links: [
            { title: 'Using the Airbnb for Work dashboard', href: '#' },
            { title: 'Account settings', href: '#' },
        ]
    },
    {
        category: 'Booking and reservations',
        links: [
            { title: 'Booking travel for employees', href: '#' },
            { title: 'Managing reservations', href: '#' },
        ]
    },
    {
        category: 'Billing and receipts',
        links: [
            { title: 'Billing', href: '#' },
            { title: 'Receipts', href: '#' },
        ]
    },
    {
        category: 'About Airbnb',
        links: [
            { title: 'Getting started', href: '#' },
            { title: 'How Airbnb works', href: '#' },
            { title: 'Our community policies', href: '#' },
            { title: 'Partnerships', href: '#' },
        ]
    },
    {
        category: 'Safety and accessibility',
        links: [
            { title: 'Safety concerns', href: '#' },
            { title: 'Safety tips and guidelines', href: '#' },
            { title: 'Reporting issues', href: '#' },
            { title: 'Government travel restrictions and advisories', href: '#' },
        ]
    }
];

export const newsArticles = [
  {
    id: 'news-1',
    title: 'Conversations with London Makr & Co.',
    author: 'Olivia Rhye',
    date: '20 Jan 2024',
    description: "We sat down with London's fast-growing brand and product design studio, Makr & Co. to find out how they've used TripsandStay to 2x their corporate travel efficiency.",
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2CRkmPfbgJ09cITKB91pHn_jEaRoN_q8N4g&s',
    hint: 'business meeting',
    tags: ['Business', 'Travel', 'Interviews'],
    href: '#',
    featured: true,
  },
  {
    id: 'news-2',
    title: 'A Relentless Pursuit of Perfection in Product Design',
    author: 'Phoenix Baker',
    date: '19 Jan 2024',
    description: "I began to notice that there was a sharp contrast between well-made and poorly-made travel accommodations. This sparked a new passion.",
    image: 'https://placehold.co/400x400.png',
    hint: 'woman thinking',
    tags: ['Design', 'Product'],
    href: '#',
    featured: false,
  },
  {
    id: 'news-3',
    title: 'How to Run a Successful Business With Your Partner',
    author: 'Lana Steiner',
    date: '18 Jan 2024',
    description: 'Starting a business with your spouse or significant other is an exciting but challenging venture. Here are our top tips.',
    image: 'https://placehold.co/400x400.png',
    hint: 'couple working',
    tags: ['Business', 'Hosting'],
    href: '#',
    featured: false,
  },
  {
    id: 'news-4',
    title: 'Why Food Matters – Disease Prevention & Treatment',
    author: 'Lana Steiner',
    date: '18 Jan 2024',
    description: 'Exploring how local culinary experiences on TripsandStay can contribute to a healthier and more enriching travel lifestyle.',
    image: 'https://placehold.co/400x400.png',
    hint: 'healthy food',
    tags: ['Health', 'Experiences'],
    href: '#',
    featured: false,
  }
];
